// <auto-generated />
using System;
using LearningManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningManagementSystem.Migrations
{
    [DbContext(typeof(LMSContext))]
    partial class LMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningManagementSystem.Models.BaiHoc", b =>
                {
                    b.Property<int>("MaBaiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiHoc"));

                    b.Property<string>("DuongDanNoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNoiDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungVanBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaiHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaBaiHoc");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.ToTable("BaiHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.BaiKiemTra", b =>
                {
                    b.Property<int>("MaBaiKiemTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiKiemTra"));

                    b.Property<int?>("BaiHocMaBaiHoc")
                        .HasColumnType("int");

                    b.Property<float>("DiemToiDa")
                        .HasColumnType("real");

                    b.Property<int>("MaBaiHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenBaiKiemTra")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaBaiKiemTra");

                    b.HasIndex("BaiHocMaBaiHoc");

                    b.ToTable("BaiKiemTra");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int?>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<float>("TienDo")
                        .HasColumnType("real");

                    b.HasKey("MaDangKy");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("DangKyKhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DichBaiHoc", b =>
                {
                    b.Property<int>("MaDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDich"));

                    b.Property<int?>("BaiHocMaBaiHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaBaiHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNgonNgu")
                        .HasColumnType("int");

                    b.Property<int?>("NgonNguMaNgonNgu")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungVanBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaiHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaDich");

                    b.HasIndex("BaiHocMaBaiHoc");

                    b.HasIndex("NgonNguMaNgonNgu");

                    b.ToTable("DichBaiHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DichKhoaHoc", b =>
                {
                    b.Property<int>("MaDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDich"));

                    b.Property<int?>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNgonNgu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NgonNguMaNgonNgu")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaDich");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.HasIndex("NgonNguMaNgonNgu");

                    b.ToTable("DichKhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.KetQuaBaiKiemTra", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<int?>("BaiKiemTraMaBaiKiemTra")
                        .HasColumnType("int");

                    b.Property<float>("DiemSo")
                        .HasColumnType("real");

                    b.Property<int>("MaBaiKiemTra")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaKetQua");

                    b.HasIndex("BaiKiemTraMaBaiKiemTra");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("KetQuaBaiKiemTra");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<int?>("DanhMucMaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("GiaoVienMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKhoaHoc");

                    b.HasIndex("DanhMucMaDanhMuc");

                    b.HasIndex("GiaoVienMaNguoiDung");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.LichSuDangNhap", b =>
                {
                    b.Property<int>("MaDangNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangNhap"));

                    b.Property<string>("DiaChiIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDangNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThongTinThietBi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaDangNhap");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("LichSuDangNhap");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.LichTrinh", b =>
                {
                    b.Property<int>("MaLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinh"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.ToTable("LichTrinh");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.NgonNgu", b =>
                {
                    b.Property<int>("MaNgonNgu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgonNgu"));

                    b.Property<string>("MaCodeNgonNgu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNgonNgu");

                    b.ToTable("NgonNgu");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("NhatKyHoatDong");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Nhom", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<int?>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhom");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.ToTable("Nhom");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.ThanhVienNhom", b =>
                {
                    b.Property<int>("MaThanhVienNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhVienNhom"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("NhomMaNhom")
                        .HasColumnType("int");

                    b.HasKey("MaThanhVienNhom");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.HasIndex("NhomMaNhom");

                    b.ToTable("ThanhVienNhom");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.TuongTac", b =>
                {
                    b.Property<int>("MaTuongTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuongTac"));

                    b.Property<int?>("BaiHocMaBaiHoc")
                        .HasColumnType("int");

                    b.Property<int?>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int?>("MaBaiHoc")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TinNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTuongTac");

                    b.HasIndex("BaiHocMaBaiHoc");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("TuongTac");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.XepHang", b =>
                {
                    b.Property<int>("MaXepHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXepHang"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<int?>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("ViTriXepHang")
                        .HasColumnType("int");

                    b.HasKey("MaXepHang");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("XepHang");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.BaiHoc", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("BaiHoc")
                        .HasForeignKey("KhoaHocMaKhoaHoc");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.BaiKiemTra", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.BaiHoc", "BaiHoc")
                        .WithMany("BaiKiemTra")
                        .HasForeignKey("BaiHocMaBaiHoc");

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHoc")
                        .HasForeignKey("KhoaHocMaKhoaHoc");

                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("DangKyKhoaHoc")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DichBaiHoc", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.BaiHoc", "BaiHoc")
                        .WithMany("DichBaiHoc")
                        .HasForeignKey("BaiHocMaBaiHoc");

                    b.HasOne("LearningManagementSystem.Models.NgonNgu", "NgonNgu")
                        .WithMany("DichBaiHoc")
                        .HasForeignKey("NgonNguMaNgonNgu");

                    b.Navigation("BaiHoc");

                    b.Navigation("NgonNgu");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DichKhoaHoc", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DichKhoaHoc")
                        .HasForeignKey("KhoaHocMaKhoaHoc");

                    b.HasOne("LearningManagementSystem.Models.NgonNgu", "NgonNgu")
                        .WithMany("DichKhoaHoc")
                        .HasForeignKey("NgonNguMaNgonNgu");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NgonNgu");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.KetQuaBaiKiemTra", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.BaiKiemTra", "BaiKiemTra")
                        .WithMany("KetQuaBaiKiemTra")
                        .HasForeignKey("BaiKiemTraMaBaiKiemTra");

                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("KetQuaBaiKiemTra")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("BaiKiemTra");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.KhoaHoc", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.DanhMuc", "DanhMuc")
                        .WithMany("KhoaHoc")
                        .HasForeignKey("DanhMucMaDanhMuc");

                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "GiaoVien")
                        .WithMany("KhoaHocGiaoVien")
                        .HasForeignKey("GiaoVienMaNguoiDung");

                    b.Navigation("DanhMuc");

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.LichSuDangNhap", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuDangNhap")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.LichTrinh", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("LichTrinh")
                        .HasForeignKey("KhoaHocMaKhoaHoc");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.NhatKyHoatDong", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyHoatDong")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Nhom", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("Nhom")
                        .HasForeignKey("KhoaHocMaKhoaHoc");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.ThanhVienNhom", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThanhVienNhom")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.HasOne("LearningManagementSystem.Models.Nhom", "Nhom")
                        .WithMany("ThanhVienNhom")
                        .HasForeignKey("NhomMaNhom");

                    b.Navigation("NguoiDung");

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.ThongBao", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBao")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.TuongTac", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.BaiHoc", "BaiHoc")
                        .WithMany("TuongTac")
                        .HasForeignKey("BaiHocMaBaiHoc");

                    b.HasOne("LearningManagementSystem.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("TuongTac")
                        .HasForeignKey("KhoaHocMaKhoaHoc");

                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("TuongTac")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("BaiHoc");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.XepHang", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("XepHang")
                        .HasForeignKey("KhoaHocMaKhoaHoc");

                    b.HasOne("LearningManagementSystem.Models.NguoiDung", "NguoiDung")
                        .WithMany("XepHang")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.BaiHoc", b =>
                {
                    b.Navigation("BaiKiemTra");

                    b.Navigation("DichBaiHoc");

                    b.Navigation("TuongTac");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.BaiKiemTra", b =>
                {
                    b.Navigation("KetQuaBaiKiemTra");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.DanhMuc", b =>
                {
                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.KhoaHoc", b =>
                {
                    b.Navigation("BaiHoc");

                    b.Navigation("DangKyKhoaHoc");

                    b.Navigation("DichKhoaHoc");

                    b.Navigation("LichTrinh");

                    b.Navigation("Nhom");

                    b.Navigation("TuongTac");

                    b.Navigation("XepHang");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.NgonNgu", b =>
                {
                    b.Navigation("DichBaiHoc");

                    b.Navigation("DichKhoaHoc");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.NguoiDung", b =>
                {
                    b.Navigation("DangKyKhoaHoc");

                    b.Navigation("KetQuaBaiKiemTra");

                    b.Navigation("KhoaHocGiaoVien");

                    b.Navigation("LichSuDangNhap");

                    b.Navigation("NhatKyHoatDong");

                    b.Navigation("ThanhVienNhom");

                    b.Navigation("ThongBao");

                    b.Navigation("TuongTac");

                    b.Navigation("XepHang");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Nhom", b =>
                {
                    b.Navigation("ThanhVienNhom");
                });
#pragma warning restore 612, 618
        }
    }
}
